const { Client, Account, TablesDB, Query, ID, Permission, Role } = Appwrite;

const CONFIG = { endpoint:'https://sgp.cloud.appwrite.io/v1', projectId:'6a88fdfe001ce0435833', databaseId:'6a8901620005cf5899f7', tableId:'attendance', userIdColumn:'User-ID', subjectColumn:'Subject', missedColumn:'Missed-Hours' };
const subjects=[['Business Accounting',45],['Business Management',30],['Introduction to AI & ML',30],['Business Communication',45],['Professional Office Applications',45],['Business Economics',30],['German Language',45],['Foundation of Indian Knowledge System',45],['Personal Growth & Awareness Lab',30],['Lifestyle & Wellness Management',30]];
const themes={aurora:'Aurora',forest:'Forest',rose:'Rose',ocean:'Ocean',graphite:'Graphite'};
const client=new Client().setEndpoint(CONFIG.endpoint).setProject(CONFIG.projectId),account=new Account(client),tables=new TablesDB(client);
const loginPanel=document.getElementById('loginPanel'),createPanel=document.getElementById('createPanel'),appPanel=document.getElementById('appPanel'),loginForm=document.getElementById('loginForm'),createForm=document.getElementById('createForm'),githubLoginButton=document.getElementById('githubLogin'),createAccountButton=document.getElementById('createAccount'),backToLogin=document.getElementById('backToLogin'),logoutButton=document.getElementById('logout'),userBadge=document.getElementById('userBadge'),subtitle=document.getElementById('subtitle'),profileLabel=document.getElementById('profileLabel'),welcome=document.getElementById('welcome'),grid=document.getElementById('grid'),message=document.getElementById('message'),themePicker=document.getElementById('themePicker'),themeToggle=document.getElementById('themeToggle'),themeMenu=document.getElementById('themeMenu'),themeLabel=document.getElementById('themeLabel');
let currentUser=null,rows=[];
function fmt(n){return Number.isInteger(Number(n))?String(n):Number(n).toFixed(2)}
function showMessage(text,error=false){message.textContent=text;message.className=`message ${error?'error':''}`}
function hideMessage(){message.className='message hidden'}
function applyTheme(theme,persist=true){if(!themes[theme])theme='aurora';document.documentElement.dataset.theme=theme;themeLabel.textContent=themes[theme];document.querySelectorAll('.theme-option').forEach(o=>o.setAttribute('aria-pressed',String(o.dataset.theme===theme)));if(persist)localStorage.setItem('attendance-theme',theme)}
function setupThemes(){applyTheme(localStorage.getItem('attendance-theme')||'aurora',false);themePicker.classList.remove('hidden');themeToggle.addEventListener('click',()=>{themeMenu.hidden=!themeMenu.hidden;themeToggle.setAttribute('aria-expanded',String(!themeMenu.hidden))});document.querySelectorAll('.theme-option').forEach(o=>o.addEventListener('click',()=>{applyTheme(o.dataset.theme);themeMenu.hidden=true;themeToggle.setAttribute('aria-expanded','false')}));document.addEventListener('click',e=>{if(!themePicker.contains(e.target)){themeMenu.hidden=true;themeToggle.setAttribute('aria-expanded','false')}})}
async function getSession(){try{return await account.get()}catch{return null}}
async function signInWithEmail(e){e.preventDefault();hideMessage();try{await account.createEmailPasswordSession(document.getElementById('email').value.trim(),document.getElementById('password').value);location.reload()}catch(error){showMessage(error.message||'Email sign-in failed.',true)}}
async function signInWithGitHub(){hideMessage();try{const r=location.href.split('#')[0];await account.createOAuth2Session('github',r,r)}catch(error){showMessage(error.message||'GitHub sign-in failed.',true)}}
async function createUser(e){e.preventDefault();hideMessage();const name=document.getElementById('createName').value.trim(),email=document.getElementById('createEmail').value.trim(),password=document.getElementById('createPassword').value,confirm=document.getElementById('confirmPassword').value;if(password!==confirm){showMessage('Passwords do not match.',true);return}try{await account.create(ID.unique(),email,password,name);await account.createEmailPasswordSession(email,password);location.reload()}catch(error){console.error(error);showMessage(error.message||'Could not create account.',true)}}
async function signOut(){try{await account.deleteSession('current')}finally{location.reload()}}
async function loadRows(){const r=await tables.listRows({databaseId:CONFIG.databaseId,tableId:CONFIG.tableId,queries:[Query.equal(CONFIG.userIdColumn,currentUser.$id),Query.limit(100)],ttl:0});return r.rows}
function rowForSubject(s){return rows.find(r=>r[CONFIG.subjectColumn]===s)}
async function saveSubject(subject,value,row){const totalHours=subjects.find(([n])=>n===subject)?.[1]??0,missed=Math.min(totalHours,Math.max(0,Number(value)||0)),data={[CONFIG.userIdColumn]:currentUser.$id,[CONFIG.subjectColumn]:subject,[CONFIG.missedColumn]:missed};if(row)await tables.updateRow({databaseId:CONFIG.databaseId,tableId:CONFIG.tableId,rowId:row.$id,data});else await tables.createRow({databaseId:CONFIG.databaseId,tableId:CONFIG.tableId,rowId:ID.unique(),data,permissions:[Permission.read(Role.user(currentUser.$id)),Permission.update(Role.user(currentUser.$id)),Permission.delete(Role.user(currentUser.$id))]})}
function buildCard(subject,totalHours,missed){missed=Math.min(totalHours,Math.max(0,Number(missed||0)));const required=totalHours*.75,canStillMiss=totalHours*.25-missed,attendance=(totalHours-missed)/totalHours*100;let status='safe',label='SAFE';if(attendance<75){status='danger';label='BELOW 75%'}else if(canStillMiss<=2){status='warn';label='CLOSE TO LIMIT'}const card=document.createElement('article');card.className='card';card.innerHTML=`<div class="card-top"><div><h3>${subject}</h3><p>${fmt(totalHours)} total hours · ${fmt(required)} required</p></div><span class="status ${status}">${label}</span></div><div class="percent">${attendance.toFixed(1)}<small>%</small></div><div class="bar"><i style="width:${Math.min(100,Math.max(0,attendance))}%"></i></div><div class="stats"><div><span>Hours missed</span><strong>${fmt(missed)} hrs</strong></div><div><span>Can still miss</span><strong>${fmt(Math.max(0,canStillMiss))} hrs</strong></div></div><label class="input-label">Hours missed<input type="number" min="0" max="${totalHours}" step="0.5" value="${missed}"></label>`;card.querySelector('input').addEventListener('change',async e=>{try{e.target.disabled=true;await saveSubject(subject,e.target.value,rowForSubject(subject));await render();showMessage('Saved.')}catch(error){showMessage(`Could not save: ${error.message||'unknown error'}`,true);e.target.disabled=false}});return card}
async function render(){rows=await loadRows();grid.innerHTML='';subjects.forEach(([s,h])=>grid.appendChild(buildCard(s,h,rowForSubject(s)?.[CONFIG.missedColumn]||0)))}
async function init(){setupThemes();loginForm?.addEventListener('submit',signInWithEmail);githubLoginButton?.addEventListener('click',signInWithGitHub);createAccountButton?.addEventListener('click',()=>{loginPanel.classList.add('hidden');createPanel.classList.remove('hidden');hideMessage()});backToLogin?.addEventListener('click',()=>{createPanel.classList.add('hidden');loginPanel.classList.remove('hidden');hideMessage()});createForm?.addEventListener('submit',createUser);try{currentUser=await getSession();if(!currentUser){loginPanel.classList.remove('hidden');createPanel.classList.add('hidden');appPanel.classList.add('hidden');return}loginPanel.classList.add('hidden');createPanel.classList.add('hidden');appPanel.classList.remove('hidden');logoutButton.classList.remove('hidden');userBadge.classList.remove('hidden');userBadge.textContent=`@${currentUser.name||currentUser.email||currentUser.$id}`;subtitle.textContent='Your attendance is stored securely in Appwrite.';profileLabel.textContent=currentUser.name||currentUser.$id;welcome.textContent=`${currentUser.name||'Your'} attendance.`;logoutButton.addEventListener('click',signOut);await render()}catch(error){console.error(error);showMessage(`Appwrite error: ${error.message||'Unable to load your attendance.'}`,true)}}
init();
